import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./UI/header";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-sky-200 w-1/5 h-screen inline flex flex-col">
          
          <Header />
          <p className="text-center text-sky-950 "> Place for some content: </p>
        </div>
        {children}
      </body>
    </html>
  );
}
