import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./header";
import Image from 'next/image'
import logo from './assets/images/Logo.png'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-sky-200 w-1/5 h-screen inline flex flex-col">
          <Image src={logo} alt="some logo" sizes="100vw"

            style={{
              width: '75%',
              height: 'auto',
              margin: '25px auto'
            }} />
          <Header />
          <p className="text-center text-sky-950 "> Place for some content: </p>
        </div>
        {children}
      </body>
    </html>
  );
}
